<?php
// @codingStandardsIgnoreFile
?>
<div class="contact-store-form">
    <div class="top-content">
        <div class="heading"><?php echo __('Contact the store') ?></div>
    </div>

    <div class="form-content">
        <form class="form contact"
              action="<?php /* @escapeNotVerified */
              echo $block->getFormAction(); ?>"
              id="contact-the-store-form"
              method="post"
              data-hasrequired="<?php /* @escapeNotVerified */
              echo __('* Required Fields') ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <div class="fieldset fieldset-row">
                    <div class="field first_name required">
                        <label class="label" for="first_name"><span><?php /* @escapeNotVerified */
                                echo __('First Name') ?></span></label>
                        <div class="control">
                            <input name="first_name" id="first_name" title="<?php /* @escapeNotVerified */
                            echo __('First Name') ?>" class="input-text" type="text"
                                   placeholder="<?php /* @escapeNotVerified */
                                   echo __('e.g. Stephanie') ?>" data-validate="{required:true}"/>
                        </div>
                    </div>
                </div>
                <div class="fieldset fieldset-row">
                    <div class="field last_name required">
                        <label class="label" for="last_name"><span><?php /* @escapeNotVerified */
                                echo __('Last Name') ?></span></label>
                        <div class="control">
                            <input name="last_name" id="last_name" title="<?php /* @escapeNotVerified */
                            echo __('Last Name') ?>" class="input-text" type="text"
                                   placeholder="<?php /* @escapeNotVerified */
                                   echo __('e.g. Smith') ?>" data-validate="{required:true}"/>
                        </div>
                    </div>
                </div>
                <div class="fieldset fieldset-row">
                    <div class="field email required">
                        <label class="label" for="email"><span><?php /* @escapeNotVerified */
                                echo __('Email address') ?></span></label>
                        <div class="control">
                            <input name="email" id="email" title="<?php /* @escapeNotVerified */
                            echo __('Email') ?>" class="input-text" type="email"
                                   placeholder="<?php /* @escapeNotVerified */
                                   echo __('e.g. smith@email.com') ?>"
                                   data-validate="{required:true, 'validate-email':true}"/>
                        </div>
                    </div>
                    <div class="field telephone">
                        <label class="label" for="telephone"><span><?php /* @escapeNotVerified */
                                echo __('Phone number <span class="small-text"> (optional) </span>') ?></span></label>
                        <div class="control">
                            <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */
                            echo __('Phone number') ?>" class="input-text" type="text"
                                   placeholder="<?php /* @escapeNotVerified */
                                   echo __('e.g. 0400 123 456') ?>"/>
                        </div>
                    </div>
                </div>
                <div class="fieldset fieldset-row wide">
                    <div class="field comment required">
                        <label class="label" for="comment"><span><?php /* @escapeNotVerified */
                                echo __('Message') ?></span></label>
                        <div class="control">
                                    <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */
                                    echo __('Message') ?>" class="input-text" cols="5" rows="3"
                                              data-validate="{required:true}"
                                              placeholder="<?php /* @escapeNotVerified */
                                              echo __('Write your message') ?>"></textarea>
                        </div>
                    </div>
                </div>

            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="hideit" id="hideit" value=""/>
                    <input type="hidden" name="store_locator_id" id="store_locator_id"
                           value="<?php echo $block->getCurrentStoreId() ?>"/>
                    <button type="submit" title="<?php /* @escapeNotVerified */
                    echo __('Submit') ?>" class="action submit primary-xsmall">
                                <span><?php /* @escapeNotVerified */
                                    echo __('Submit') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>