<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>

<?php
$_productCollection = $block->getCourseProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_cashbackHelper = $this->helper('CameraHouse\CashBack\Helper\Data');
$_stockStatusHelper = $this->helper('CameraHouse\Catalog\Helper\Stock\Status');
$_brandCollectionHelper = $this->helper('CameraHouse\Brand\Helper\Data');
$_courseHelper = $this->helper('CameraHouse\Course\Helper\Data');
?>

<?php
$_brandCollection = $_brandCollectionHelper->getBrandCollection();
?>
<?php if ($_productCollection->count()): ?>
    <?php
    //Always display as a list
    $viewMode = 'list';
    $image = 'category_page_list';
    //$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getListProductBlock()->getPositioned();
    ?>
    <div id="course-products">
        <div class="page-title-wrapper">
            <h2 class="page-title" id="page-title-heading" aria-labelledby="page-title-heading toolbar-amount">
                <span class="base" data-ui-id="page-title-wrapper"><?php echo __('Courses'); ?></span></h2>
        </div>

        <div class="products wrapper <?php /* @escapeNotVerified */
        echo $viewMode; ?> products-<?php /* @escapeNotVerified */
        echo $viewMode; ?>">
            <?php $iterator = 1; ?>
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <?php /* @escapeNotVerified */
                    echo ($iterator++ == 1) ? '<li class="item product product-item product-type-'.strtolower($_product->getTypeId()).'">' : '</li><li class="item product product-item product-type-'.strtolower($_product->getTypeId()).'">' ?>
                    <div
                        class="product-item-info<?php echo (!empty($_product->getCourseDate())) ? ' course-product' : ''; ?>"
                        data-container="product-grid">


                        <div class="img-wraper">

                            <!--Start - Brand Logo-->
                            <div class="brand-name"><?php
                                if (empty($_product->getCourseDate())):
                                    if (key_exists($_product->getBrand(), $_brandCollection)):
                                        ?><a class="brand brand-name" href="<?php echo $_product->getProductUrl(); ?>">
                                        <img
                                            src="<?php echo $_brandCollection[$_product->getBrand()]['image']; ?>"
                                            alt="<?php echo $_brandCollection[$_product->getBrand()]['name']; ?>"/>
                                        </a><?php
                                    endif;
                                else: ?><a class="brand brand-name">
                                    <img src="<?php echo $_courseHelper->getCourseLogo(); ?>" alt="Course Product"/>
                                    </a><?php endif; ?></div>


                            <!--END - Brand Logo-->

                            <?php
                            $productImage = $block->getListProductBlock()->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <a href="<?php /* @escapeNotVerified */
                            echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                        </div>
                        <div class="product details product-item-details">

                            <div
                                class="list-item-middle <?php echo $_cashbackHelper->hasCashback($_product) ? "cashback" : ""; ?>">

                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php /* @escapeNotVerified */
                                       echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>


                                <div
                                    class="list-item-bonus<?php echo $_cashbackHelper->hasCashback($_product) ? " cashback-available" : ""; ?> <?php echo "product-type-" . strtolower($_product->getTypeId()) ?>">


                                    <?php if (!empty($_product->getCourseDate())): ?>

                                        <ul>
                                            <?php if (!empty($_product->getCourseDate())): ?>
                                                <li class="course-date"><span
                                                        class="highlight"><?php echo __('When') . ':'; ?></span><?php
                                                    $date = new \DateTime($_product->getCourseDate());
                                                    $dateTime = $date->format('d M Y h:i a');
                                                    echo $dateTime;
                                                    ?></li>
                                            <?php endif; ?>

                                            <?php if (!empty($_product->getComplexityValue())): ?>
                                                <li class="course-complexity"><span
                                                        class="highlight"><?php echo __('Complexity') . ':'; ?></span><?php echo $_product->getComplexityValue(); ?>
                                                </li>
                                            <?php endif; ?>

                                            <?php if ($_product->getStreetOne() != '' || $_product->getStreetTwo() != '' || $_product->getSuburb() != '' || $_product->getCourseState() != '' || $_product->getPostcode() != ''): ?>
                                                <li class="course-location"><span
                                                        class="highlight"><?php echo __('Location') . ':'; ?></span>

                                                    <?php if (!empty($_product->getStreetOne())): ?><span
                                                        class="location-line"><?php echo $_product->getStreetOne(); ?></span><?php endif; ?>

                                                    <?php if (!empty($_product->getStreetTwo())): ?><span
                                                        class="location-line"><?php echo $_product->getStreetTwo(); ?></span><?php endif; ?>

                                                    <?php if ($_product->getSuburb() != '' || $_product->getCourseState() != '' || $_product->getPostcode() != ''): ?>
                                                        <span class="location-line">
                                                        <?php echo $_product->getSuburb(); ?>
                                                        <?php echo $_product->getCourseStateValue(); ?>
                                                        <?php echo $_product->getPostcode(); ?>
                                                    </span>
                                                    <?php endif; ?>

                                                </li>
                                            <?php endif; ?>

                                            <?php if (!empty($_product->getCourseStore())): ?>
                                                <li class="course-store"><span
                                                        class="highlight"><?php echo __('Offered by') . ':'; ?></span><?php echo $_product->getAttributeText('course_store'); ?>
                                                </li>
                                            <?php endif; ?>
                                        </ul>

                                    <?php endif; ?>

                                </div>
                            </div>
                            <div
                                class="list-item-right <?php echo $_cashbackHelper->hasCashback($_product) ? "cashback" : ""; ?>">
                                <?php /* @escapeNotVerified */
                                echo $block->getProductPrice($_product) ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?php echo strpos($pos,
                                        $viewMode . '-actions') ? $position : ''; ?>>
                                        <div class="actions-primary"<?php echo strpos($pos,
                                            $viewMode . '-primary') ? $position : ''; ?>>


                                            <?php $stockStatus = $_stockStatusHelper->stockStatus($_product); ?>

                                            <div class="stock <?php echo $stockStatus['class']; ?>">
                                            <span>
                                                <?php if ($stockStatus['link']): ?><a href="javascript:void(null);"
                                                                                      onclick="parent.LC_API.open_chat_window();"><?php endif; ?>
                                                    <?php /* @escapeNotVerified */
                                                    echo __($stockStatus['text']) ?>
                                                    <?php if ($stockStatus['link']): ?></a><?php endif; ?>
                                            </span>
                                            </div>

                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>

                                                <?php if ($_product->getTypeId() == 'kit'): ?>
                                                    <button type="button"
                                                            title="<?php echo $block->escapeHtml(__('See Kit Options')); ?>"
                                                            class="action tocart primary"
                                                            onclick="window.location='<?php /* @escapeNotVerified */
                                                            echo $_product->getProductUrl() ?>'">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('See Kit Options') ?></span>

                                                    </button>
                                                <?php else: ?>

                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                                    echo $postParams['action']; ?>" method="post">
                                                        <input type="hidden" name="product"
                                                               value="<?php /* @escapeNotVerified */
                                                               echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="<?php /* @escapeNotVerified */
                                                        echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                               value="<?php /* @escapeNotVerified */
                                                               echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                        <?php echo $block->getBlockHtml('formkey') ?>
                                                        <?php $_adToCartBtnTxt = 'Add to Cart'; ?>

                                                        <?php if ($_product->getTypeId() == 'kit'): ?>
                                                            <?php $_adToCartBtnTxt = 'See Kit Options'; ?>

                                                        <?php elseif ($_product->getPreOrder() == '1' && $_product->getTypeId() != 'grouped'): ?>
                                                            <?php $_adToCartBtnTxt = 'Pre-Order'; ?>

                                                        <?php endif; ?>

                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__($_adToCartBtnTxt)); ?>"
                                                                class="action tocart primary">
                                                        <span><?php /* @escapeNotVerified */
                                                            echo __($_adToCartBtnTxt) ?></span>

                                                        </button>
                                                    </form>

                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos,
                                            $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
    <?php if (!$block->getListProductBlock()->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>
